"""empty message

Revision ID: 4d344a980d75
Revises: 1beeb18a2396
Create Date: 2023-04-14 13:13:28.414957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d344a980d75'
down_revision = '1beeb18a2396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("unique_email", ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
