#!/bin/bash
#script for running the container locally
sudo docker run \
  --rm \
  --name kontener \
  -p 5000:5000 \
  -w /app \
  -v "$(pwd)/app:/app" \
  rest-api \
  sh -c "flask run --host 0.0.0.0"
